Adding support for syntax highlighting for Helm Inspect Values
Azure/vscode-kubernetes-tools pull request #903
Opened 2021-03-07 04:36 UTC by shreyaskarnik

This PR follows the enhancement request #891 and implements a new command `Generate values.yaml` for Helm Repo Explorer which generates a `values.yaml` file for the Helm chart. 

![image](https://user-images.githubusercontent.com/311217/110229056-6695a780-7ebb-11eb-89ed-c39625ca175f.png)

The primary use case for this `values.yaml` file is syntax highlighting and generation of editable `values.yaml` file which can enable customization of Helm chart installation.

Since this functionality is closely related to Helm Inspect Values I have implemented this as an extension of the same. Happy to provide alternate implementation if necessary.

2021-03-10 16:34 UTC, lstocchi requested changes
Sorry for the late response. I still haven't had the time to play with it, i'll do it tomorrow, promise. I added some comments based on a first look.

BTW thanks for your contribution. Super as usual :rocket:

2021-03-11 15:14 UTC, lstocchi commented
@shreyaskarnik you're welcome :) . Played with it a bit. In addition to the comments above, a thing i think we can improve is the naming of the yaml. I guess we can add the name + version of what we are inspecting.
If i have some tabs opened it's very easy to get lost.
![image](https://user-images.githubusercontent.com/49404737/110808560-64996300-8284-11eb-8eee-e94ee4b165fd.png)

2021-03-11 17:32 UTC, shreyaskarnik commented
@lstocchi great suggestion, will add that in

2021-03-22 19:02 UTC, shreyaskarnik commented
Have been heads down on a work project for the past couple of weeks. I will make changes as I free up.

2021-04-12 00:01 UTC, shreyaskarnik commented on package.json
> +        "onCommand:extension.helmGetValues",
made change in name according to suggestion

2021-04-12 00:01 UTC, shreyaskarnik commented on src/helm.exec.ts
> +            getFile(uri);
changed name according to the suggestion

2021-04-12 00:02 UTC, shreyaskarnik commented on src/helm.exec.ts
> +        const generateFile = s.generateFile ? `&generateFile=values.yaml` : "";
changed to simplify

2021-04-12 00:02 UTC, shreyaskarnik commented on src/helm.documentProvider.ts
> +                const generateFile = (query.generateFile as string) ? true : false;
changed to simplify according to suggestion

2021-04-12 00:03 UTC, shreyaskarnik commented on src/helm.documentProvider.ts
> +                const version = query.version as string;
changed and tested to make sure undefined values are handled

2021-04-12 00:09 UTC, shreyaskarnik commented
@lstocchi I have made changes to the PR based on your comments. Also made the following change to reflect chart name/version in the generated `values.yaml` file.
![image](https://user-images.githubusercontent.com/311217/114326123-11ffd080-9ae8-11eb-9cec-974bbbc8cf13.png)
when clicked on top level chart name
![image](https://user-images.githubusercontent.com/311217/114326137-2217b000-9ae8-11eb-8882-77d2a9f35b5d.png)

when clicked on a specific version 
![image](https://user-images.githubusercontent.com/311217/114326151-3491e980-9ae8-11eb-9823-53a1abcff161.png)
![image](https://user-images.githubusercontent.com/311217/114326156-3f4c7e80-9ae8-11eb-8c96-868e00a08d1e.png)

let me know your thoughts. I am new to TypeScript so if there are any syntactic issues that I have overlooked please let me know.

2021-04-13 13:03 UTC, lstocchi requested changes
@shreyaskarnik no need to apologize, we don't have any rush. We really appreciate your help in improving this extension :)

Regarding the PR, it looks good the final behavior. Added some comments below to clean the code a bit but nothing blocking, if you don't have time to work on them just let me know. Thanks!!

2021-04-15 23:04 UTC, shreyaskarnik commented on src/helm.documentProvider.ts
> +            const filePrinter = (code: number, out: string, err: string) => {
realized that it was copy pasted so I have made the functions inline and have added appropriate error messages. I tried extracting the function but was not successful with the promise in play.

2021-04-15 23:04 UTC, shreyaskarnik commented on src/helm.documentProvider.ts
> +                const generateFile = query.generateFile  ? true : false;
done

2021-04-15 23:04 UTC, shreyaskarnik commented on src/utils/preview.ts
> +        vscode.window.showTextDocument(document);
Thanks for the tip added this.

2021-04-15 23:06 UTC, shreyaskarnik commented on src/helm.exec.ts
> +        if (s.generateFile) {
simplified the logic to become localized with the if/else blocks. Can improvise if the repetition needs to be avoided.

2021-04-17 14:34 UTC, lstocchi approved these changes
Thanks for all the changes @shreyaskarnik . LGTM.
Can you please give this a look? You know Helm better than me @bacongobbler @itowlson  Thanks!!

2021-04-19 01:26 UTC, itowlson approved these changes
Looks good to me @shreyaskarnik - thanks!  I'd like to get a final check from @bacongobbler as the local Helm whiz, but otherwise I think this is good to go.

2021-04-19 22:13 UTC, bacongobbler commented
Thanks @shreyaskarnik for tackling this.

I'm curious about the choice to make this a new command instead of re-using the existing "Inspect values" command in the UI.

Can you clarify when someone would want to choose "Inspect values" over "Generate values.yaml"? Do their use cases overlap, or are they discretely different? Because looking at #891 I thought the idea was to make the output of "Inspect values" editable.

Thanks!

2021-04-19 23:18 UTC, shreyaskarnik commented
@bacongobbler Thanks for the feedback. Initially, I was thinking the same. I cannot think of a scenario where I would fall back to the original `Inspect Values` functionality after trying out the `Generate values.yaml` command. If there is consensus for replacing `Inspect Values` with `Generate values.yaml` I am all in for that and should be able to provide a quick turnaround on the PR with required changes.

2021-04-20 02:21 UTC, itowlson commented
If @bacongobbler is happy with one command then I am too, but I would suggest that we not name that command "Inspect" if it allows editing.  I don't know if Edit Values or Generate Values or what is right though - Fisher?  (I am happy to keep the original command ID, or to use your new one, regardless of what the unified command ends up being called in the UI.)

2021-04-20 14:55 UTC, bacongobbler commented
Yeah.. Something like "Fetch values" might be more prudent. `helm inspect values` loads the chart then returns the values... In reality this is just returning the values.yaml from the chart, but it might include chart dependency values in the subtree as well (can't remember). I have no strong opinions whether to rename it vs keeping it as-is.

2021-04-21 17:38 UTC, shreyaskarnik commented
@bacongobbler and @itowlson thanks for the comments, I will revise the PR to include the `Fetch values` command in the context menu soon.

2021-04-24 23:44 UTC, shreyaskarnik commented
I have made the changes discussed in this thread and added `Fetch values`

2021-04-26 21:15 UTC, itowlson approved these changes
Thanks for the update!  Good to go now I think!

2021-04-26 22:09 UTC, bacongobbler approved these changes

2021-04-26 22:56 UTC, merged